// <auto-generated />
using APIPagingFilterMapperEx.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPagingFilterMapperEx.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20250916144026_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIPagingFilterMapperEx.Models.Category", b =>
                {
                    b.Property<long>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1L,
                            CategoryName = "Computer"
                        },
                        new
                        {
                            CategoryID = 2L,
                            CategoryName = "Home Appliances"
                        });
                });

            modelBuilder.Entity("APIPagingFilterMapperEx.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductID"));

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("MfgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1L,
                            CategoryID = 1L,
                            MfgName = "Intex",
                            Price = 450m,
                            ProductName = "Mouse"
                        },
                        new
                        {
                            ProductID = 2L,
                            CategoryID = 1L,
                            MfgName = "Logitech",
                            Price = 950m,
                            ProductName = "Keyboard"
                        },
                        new
                        {
                            ProductID = 3L,
                            CategoryID = 2L,
                            MfgName = "Bosh",
                            Price = 55550m,
                            ProductName = "Washing Machine"
                        },
                        new
                        {
                            ProductID = 4L,
                            CategoryID = 2L,
                            MfgName = "LG",
                            Price = 85550m,
                            ProductName = "LED TV"
                        },
                        new
                        {
                            ProductID = 5L,
                            CategoryID = 2L,
                            MfgName = "Bosh",
                            Price = 45550m,
                            ProductName = "Dish Washer"
                        },
                        new
                        {
                            ProductID = 6L,
                            CategoryID = 1L,
                            MfgName = "Lenovo",
                            Price = 15550m,
                            ProductName = "Web CAM"
                        },
                        new
                        {
                            ProductID = 7L,
                            CategoryID = 1L,
                            MfgName = "Segate",
                            Price = 13550m,
                            ProductName = "Hard Disk"
                        });
                });

            modelBuilder.Entity("APIPagingFilterMapperEx.Models.Product", b =>
                {
                    b.HasOne("APIPagingFilterMapperEx.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
